/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S4_PoligonosRegulares;

import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Segura Vidal
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    String mensajeError = "";
    int numLados=0;
    double valorLado=0;
    int error = 0;
    double perimetro = 0;
    double area = 0;
    double apotema = 0;
    int tipo = 0;
    
    public MenuPrincipal() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        mensaje();
    }
    
    
    public void validar () throws NumberFormatException
    {
        try
        {

            numLados = Integer.parseInt(jTNumLados.getText());

            valorLado = Integer.parseInt(jTValorLado.getText());

            if (numLados <= 0 )
            {
               error = 1;
               jTNumLados.setText("Numero no valido");
               throw new NumberFormatException();
            }

            if (valorLado <= 0)
            {
               error = 1;
               jTValorLado.setText("Numero no valido");
               throw new NumberFormatException();
            }
        }
        catch (NumberFormatException e)
        {    
            mensajeError = "El numero ingresado no es valido"; 
        
            JOptionPane.showMessageDialog(null, mensajeError);
        }
    }
    
    public void mensaje ()
    {
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de calculo "
                                          + "\nde area de poligonos regulares");
    }
    
    public void obtenerDatos ()
    {
        numLados = Integer.parseInt(jTNumLados.getText());
        valorLado = Double.parseDouble(jTValorLado.getText());
    }
            
    public void calcPerimetro ()
    {
        perimetro = numLados * valorLado;
    }
    
    public void calcApotema ()
    {
        apotema = (valorLado)/2*Math.tan(Math.toRadians(180/numLados));
    }
    
    public void calcArea ()
    {
        area = (apotema*perimetro)/2;
    }
    
    public void mostrarDatos ()
    {
        jLTitulo.setText("Resultado");
        jLSub1.setText("Area");
        jLSub2.setText("Perimetro");
        
        jTNumLados.setText(area+"");
        jTValorLado.setText(perimetro+"");
        
        jBCalcular.setText("Listo");
        
        tipo = 1;
    }
    
    public void limpiar ()
    {
        jLTitulo.setText("Introduzca los datos");
        jLSub1.setText("Numero de lados");
        jLSub2.setText("Valor del Lado");
        
        jTNumLados.setText("1,2,3,4,5");
        jTValorLado.setText("1,2,3,4,5");
        
        jBCalcular.setText("Calcular");
        
        tipo = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLSub1 = new javax.swing.JLabel();
        jTNumLados = new javax.swing.JTextField();
        jLSub2 = new javax.swing.JLabel();
        jTValorLado = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Introduzca los datos");

        jLSub1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLSub1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSub1.setText("Numero de Lados");

        jTNumLados.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jTNumLados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNumLados.setText("1,2,3,4....");

        jLSub2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLSub2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSub2.setText("Valor del lado");

        jTValorLado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jTValorLado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTValorLado.setText("1,2,3,4....");

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTNumLados))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTValorLado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jBCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLSub1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNumLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLSub2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTValorLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        if (tipo == 0)
        {
            validar();
            obtenerDatos();
            calcPerimetro();
            calcApotema();
            calcArea();
            mostrarDatos();
        }
        else
        {
            int resp = JOptionPane.showOptionDialog(null,
            "¿Desea comprobar otro poligono?",
            null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, null, null);
            
            if (resp == 0)
            {
                limpiar ();
            }
            else
            {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jBCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLSub1;
    private javax.swing.JLabel jLSub2;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTNumLados;
    private javax.swing.JTextField jTValorLado;
    // End of variables declaration//GEN-END:variables
}
