/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceFinal;

import javax.swing.JPanel;

import S2_PlanoTriangulo.*;
import S3_notas.*;
import S3_Cuadrado.*;
import S4_AnalisisPersona.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Segura Vidal
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void abrirPagina (JPanel panel)
    {
        if (panel == jPPagina5)
        {
            jPPagina5.setVisible(true);
            jPPagina6.setVisible(false);
            jPPagina7.setVisible(false);
            jPPagina8.setVisible(false); 
        }
        else
        {
            if (panel == jPPagina6)
            {
                jPPagina6.setVisible(true);
                jPPagina5.setVisible(false);
                jPPagina7.setVisible(false);
                jPPagina8.setVisible(false);
            }
            else
            {
                if (panel == jPPagina7)
                {
                    jPPagina7.setVisible(true);
                    jPPagina6.setVisible(false);
                    jPPagina5.setVisible(false);
                    jPPagina8.setVisible(false);
                }
                else
                {
                    jPPagina8.setVisible(true);
                    jPPagina5.setVisible(false);
                    jPPagina6.setVisible(false);
                    jPPagina7.setVisible(false);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMarco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPPagina1 = new javax.swing.JPanel();
        jBP1E4 = new javax.swing.JButton();
        jBP1E1 = new javax.swing.JButton();
        jBP1E2 = new javax.swing.JButton();
        jBP1E3 = new javax.swing.JButton();
        jPPagina2 = new javax.swing.JPanel();
        jBP2E4 = new javax.swing.JButton();
        jBP2E1 = new javax.swing.JButton();
        jBP2E2 = new javax.swing.JButton();
        jBP2E3 = new javax.swing.JButton();
        jPPagina3 = new javax.swing.JPanel();
        jBP3E4 = new javax.swing.JButton();
        jBP3E1 = new javax.swing.JButton();
        jBP3E2 = new javax.swing.JButton();
        jBP3E3 = new javax.swing.JButton();
        jPPagina4 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jBPage1 = new javax.swing.JButton();
        jBPage2 = new javax.swing.JButton();
        jBPage3 = new javax.swing.JButton();
        jBPage4 = new javax.swing.JButton();
        jPMarco1 = new javax.swing.JPanel();
        jPPagina5 = new javax.swing.JPanel();
        jBP1E5 = new javax.swing.JButton();
        jBP1E6 = new javax.swing.JButton();
        jBP1E7 = new javax.swing.JButton();
        jBP1E8 = new javax.swing.JButton();
        jBP1E9 = new javax.swing.JButton();
        jPPagina6 = new javax.swing.JPanel();
        jBP2E5 = new javax.swing.JButton();
        jBP2E6 = new javax.swing.JButton();
        jBP2E7 = new javax.swing.JButton();
        jBP2E8 = new javax.swing.JButton();
        jPPagina7 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPPagina8 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPMarco.setOpaque(false);
        jPMarco.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/marco.png"))); // NOI18N
        jPMarco.add(jLabel1, "card5");

        jPPagina1.setOpaque(false);
        jPPagina1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBP1E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E4.png"))); // NOI18N
        jBP1E4.setBorderPainted(false);
        jBP1E4.setContentAreaFilled(false);
        jPPagina1.add(jBP1E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 262, 470, 80));

        jBP1E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E1.png"))); // NOI18N
        jBP1E1.setBorderPainted(false);
        jBP1E1.setContentAreaFilled(false);
        jPPagina1.add(jBP1E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jBP1E2.setBorderPainted(false);
        jBP1E2.setContentAreaFilled(false);
        jPPagina1.add(jBP1E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jBP1E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E3.png"))); // NOI18N
        jBP1E3.setBorderPainted(false);
        jBP1E3.setContentAreaFilled(false);
        jPPagina1.add(jBP1E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco.add(jPPagina1, "card3");

        jPPagina2.setOpaque(false);
        jPPagina2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBP2E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E4.png"))); // NOI18N
        jBP2E4.setBorderPainted(false);
        jBP2E4.setContentAreaFilled(false);
        jPPagina2.add(jBP2E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jBP2E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E1.png"))); // NOI18N
        jBP2E1.setBorderPainted(false);
        jBP2E1.setContentAreaFilled(false);
        jPPagina2.add(jBP2E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jBP2E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E2.png"))); // NOI18N
        jBP2E2.setBorderPainted(false);
        jBP2E2.setContentAreaFilled(false);
        jPPagina2.add(jBP2E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jBP2E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E3.png"))); // NOI18N
        jBP2E3.setBorderPainted(false);
        jBP2E3.setContentAreaFilled(false);
        jPPagina2.add(jBP2E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco.add(jPPagina2, "card3");

        jPPagina3.setOpaque(false);
        jPPagina3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBP3E4.setBorderPainted(false);
        jBP3E4.setContentAreaFilled(false);
        jPPagina3.add(jBP3E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jBP3E1.setBorderPainted(false);
        jBP3E1.setContentAreaFilled(false);
        jBP3E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP3E1ActionPerformed(evt);
            }
        });
        jPPagina3.add(jBP3E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jBP3E2.setBorderPainted(false);
        jBP3E2.setContentAreaFilled(false);
        jPPagina3.add(jBP3E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jBP3E3.setBorderPainted(false);
        jBP3E3.setContentAreaFilled(false);
        jPPagina3.add(jBP3E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco.add(jPPagina3, "card3");

        jPPagina4.setOpaque(false);
        jPPagina4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E2.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jPPagina4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E1.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPPagina4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E1.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jPPagina4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E2.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jPPagina4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco.add(jPPagina4, "card3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BPage1_2.png"))); // NOI18N
        jBPage1.setBorderPainted(false);
        jBPage1.setContentAreaFilled(false);
        jBPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 435, 30, 50));

        jBPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BPage2_2.png"))); // NOI18N
        jBPage2.setBorderPainted(false);
        jBPage2.setContentAreaFilled(false);
        jBPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 435, 30, 50));

        jBPage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BPage3_2.png"))); // NOI18N
        jBPage3.setBorderPainted(false);
        jBPage3.setContentAreaFilled(false);
        jBPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 435, 30, 50));

        jBPage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BPage4_2.png"))); // NOI18N
        jBPage4.setBorderPainted(false);
        jBPage4.setContentAreaFilled(false);
        jBPage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 435, 30, 50));

        jPMarco1.setOpaque(false);
        jPMarco1.setLayout(new java.awt.CardLayout());

        jPPagina5.setOpaque(false);
        jPPagina5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBP1E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E4.png"))); // NOI18N
        jBP1E5.setBorderPainted(false);
        jBP1E5.setContentAreaFilled(false);
        jBP1E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP1E5ActionPerformed(evt);
            }
        });
        jPPagina5.add(jBP1E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 262, 470, 80));

        jBP1E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E2.png"))); // NOI18N
        jBP1E6.setBorderPainted(false);
        jBP1E6.setContentAreaFilled(false);
        jBP1E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP1E6ActionPerformed(evt);
            }
        });
        jPPagina5.add(jBP1E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 97, 470, 80));

        jBP1E7.setBorderPainted(false);
        jBP1E7.setContentAreaFilled(false);
        jPPagina5.add(jBP1E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jBP1E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E3.png"))); // NOI18N
        jBP1E8.setBorderPainted(false);
        jBP1E8.setContentAreaFilled(false);
        jBP1E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP1E8ActionPerformed(evt);
            }
        });
        jPPagina5.add(jBP1E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jBP1E9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E1.png"))); // NOI18N
        jBP1E9.setBorderPainted(false);
        jBP1E9.setContentAreaFilled(false);
        jBP1E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP1E9ActionPerformed(evt);
            }
        });
        jPPagina5.add(jBP1E9, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jPMarco1.add(jPPagina5, "card3");

        jPPagina6.setOpaque(false);
        jPPagina6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBP2E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E4.png"))); // NOI18N
        jBP2E5.setBorderPainted(false);
        jBP2E5.setContentAreaFilled(false);
        jPPagina6.add(jBP2E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jBP2E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP1E5.png"))); // NOI18N
        jBP2E6.setBorderPainted(false);
        jBP2E6.setContentAreaFilled(false);
        jBP2E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBP2E6ActionPerformed(evt);
            }
        });
        jPPagina6.add(jBP2E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jBP2E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E2.png"))); // NOI18N
        jBP2E7.setBorderPainted(false);
        jBP2E7.setContentAreaFilled(false);
        jPPagina6.add(jBP2E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jBP2E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP2E3.png"))); // NOI18N
        jBP2E8.setBorderPainted(false);
        jBP2E8.setContentAreaFilled(false);
        jPPagina6.add(jBP2E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco1.add(jPPagina6, "card3");

        jPPagina7.setOpaque(false);
        jPPagina7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jPPagina7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonP3E1.png"))); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPPagina7.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jPPagina7.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jPPagina7.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco1.add(jPPagina7, "card3");

        jPPagina8.setOpaque(false);
        jPPagina8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jPPagina8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 470, 80));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPPagina8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 470, 80));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jPPagina8.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 470, 80));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vacio.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jPPagina8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 180, 470, 80));

        jPMarco1.add(jPPagina8, "card3");

        getContentPane().add(jPMarco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 620, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Wallpaper.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBP3E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP3E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBP3E1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jBPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage1ActionPerformed
        abrirPagina(jPPagina5);
    }//GEN-LAST:event_jBPage1ActionPerformed

    private void jBPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage2ActionPerformed
        abrirPagina(jPPagina6);
    }//GEN-LAST:event_jBPage2ActionPerformed

    private void jBPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage3ActionPerformed
        abrirPagina(jPPagina7);
    }//GEN-LAST:event_jBPage3ActionPerformed

    private void jBPage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage4ActionPerformed
        abrirPagina(jPPagina8);
    }//GEN-LAST:event_jBPage4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jBP1E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP1E5ActionPerformed
        CursoPromedio  cursoP = new CursoPromedio();

        cursoP.cargarDatos("/src/PracticaSemanaIII");
        cursoP.promedio();
        cursoP.notaMaxima();
        cursoP.notaMinima();
        cursoP.deviacion();
        JOptionPane.showMessageDialog(null, cursoP.toString());
    }//GEN-LAST:event_jBP1E5ActionPerformed

    private void jBP1E9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP1E9ActionPerformed
        double[] lados = new double[3];

        for (int i = 0;i<3;i++)
        {
            lados[i] = Double.parseDouble(JOptionPane.showInputDialog("Digite el lado #"+(i+1)));
        }

        Triangulo tri1 = new Triangulo(lados[0], lados[1], lados[2]);

        tri1.ladoMayor();

        JOptionPane.showMessageDialog(null, tri1.toString(tri1.equilatero()));
       
    }//GEN-LAST:event_jBP1E9ActionPerformed

    private void jBP1E8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP1E8ActionPerformed
        
        boolean seguirCuadrado = true; 
        
        String mensaje = "Digite valores validos";
        
        double ladoCuadrado = 0;

        while (seguirCuadrado)
        {    
          try
          {  ladoCuadrado = Double.parseDouble(JOptionPane.showInputDialog("Digite el lado"));

            if (ladoCuadrado == 0 || ladoCuadrado < 0)
            {
                 seguirCuadrado = true;
                 mensaje = "El lado debe de ser positvo";
            }
            
            seguirCuadrado = false;
            
          }
          catch (NumberFormatException e)
          {
              JOptionPane.showMessageDialog(null,mensaje); 
          }
        }

//         Cuadrado cube = new Cuadrado(ladoCuadrado);
//         cube.areaPerimetro();
//         JOptionPane.showMessageDialog(null,cube.toString());
    }//GEN-LAST:event_jBP1E8ActionPerformed

    private void jBP1E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP1E6ActionPerformed
       int[] cordenadas = new int[2];

        for (int i =0;i<2;i++)
        {
            String[] cor = {"x","y"};

            cordenadas [i] = Integer.parseInt(JOptionPane.showInputDialog("Digite la cordenada en "+cor[i]));
        }

        PlanoCartesiano pc = new PlanoCartesiano(cordenadas[0],cordenadas[1]);

        pc.cordenada();
        pc.cuadrante();
        pc.calcDistancia();
        JOptionPane.showMessageDialog(null,pc.toString());
    }//GEN-LAST:event_jBP1E6ActionPerformed

    private void jBP2E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBP2E6ActionPerformed
        Formulario formulario = new Formulario();
        formulario.setVisible(true);
    }//GEN-LAST:event_jBP2E6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBP1E1;
    private javax.swing.JButton jBP1E2;
    private javax.swing.JButton jBP1E3;
    private javax.swing.JButton jBP1E4;
    private javax.swing.JButton jBP1E5;
    private javax.swing.JButton jBP1E6;
    private javax.swing.JButton jBP1E7;
    private javax.swing.JButton jBP1E8;
    private javax.swing.JButton jBP1E9;
    private javax.swing.JButton jBP2E1;
    private javax.swing.JButton jBP2E2;
    private javax.swing.JButton jBP2E3;
    private javax.swing.JButton jBP2E4;
    private javax.swing.JButton jBP2E5;
    private javax.swing.JButton jBP2E6;
    private javax.swing.JButton jBP2E7;
    private javax.swing.JButton jBP2E8;
    private javax.swing.JButton jBP3E1;
    private javax.swing.JButton jBP3E2;
    private javax.swing.JButton jBP3E3;
    private javax.swing.JButton jBP3E4;
    private javax.swing.JButton jBPage1;
    private javax.swing.JButton jBPage2;
    private javax.swing.JButton jBPage3;
    private javax.swing.JButton jBPage4;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPMarco;
    private javax.swing.JPanel jPMarco1;
    private javax.swing.JPanel jPPagina1;
    private javax.swing.JPanel jPPagina2;
    private javax.swing.JPanel jPPagina3;
    private javax.swing.JPanel jPPagina4;
    private javax.swing.JPanel jPPagina5;
    private javax.swing.JPanel jPPagina6;
    private javax.swing.JPanel jPPagina7;
    private javax.swing.JPanel jPPagina8;
    // End of variables declaration//GEN-END:variables
}
