/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceFinal;

/**
 *
 * @author Sergio Segura Vidal
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiarPantalla(1);
    }
    
    public void limpiarPantalla (int page)
    {
       if (page == 1)
       {
            this.jBEje1.setVisible(true);
            this.jBEje2.setVisible(true);
            this.jBEje3.setVisible(true);
            this.jBEje4.setVisible(true);

            this.jBEje5.setVisible(false);
            this.jBEje6.setVisible(false);
            this.jBEje7.setVisible(false);
            this.jBEje8.setVisible(false);
            this.jBEje9.setVisible(false);
            this.jBEje10.setVisible(false);
            this.jBEje11.setVisible(false);
            this.jBEje12.setVisible(false);
       }
       else
       {
           if (page == 2)
           {
                this.jBEje5.setVisible(true);
                this.jBEje6.setVisible(true);
                this.jBEje7.setVisible(true);
                this.jBEje8.setVisible(true); 
               
                this.jBEje1.setVisible(false);
                this.jBEje2.setVisible(false);
                this.jBEje3.setVisible(false);
                this.jBEje4.setVisible(false);
                this.jBEje9.setVisible(false);
                this.jBEje10.setVisible(false);
                this.jBEje11.setVisible(false);
                this.jBEje12.setVisible(false);
           }
           else
           {
               if(page == 3)
               {
                    this.jBEje9.setVisible(true);
                    this.jBEje10.setVisible(true);
                    this.jBEje11.setVisible(true);
                    this.jBEje12.setVisible(true); 
                   
                    this.jBEje1.setVisible(false);
                    this.jBEje2.setVisible(false);
                    this.jBEje3.setVisible(false);
                    this.jBEje4.setVisible(false);
                    this.jBEje5.setVisible(false);
                    this.jBEje6.setVisible(false);
                    this.jBEje7.setVisible(false);
                    this.jBEje8.setVisible(false);
               }
           }
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBPage1 = new javax.swing.JButton();
        jBPage2 = new javax.swing.JButton();
        jBPage3 = new javax.swing.JButton();
        jBEje1 = new javax.swing.JButton();
        jBEje2 = new javax.swing.JButton();
        jBEje3 = new javax.swing.JButton();
        jBEje4 = new javax.swing.JButton();
        jBEje5 = new javax.swing.JButton();
        jBEje6 = new javax.swing.JButton();
        jBEje7 = new javax.swing.JButton();
        jBEje8 = new javax.swing.JButton();
        jBEje9 = new javax.swing.JButton();
        jBEje11 = new javax.swing.JButton();
        jBEje12 = new javax.swing.JButton();
        jBEje10 = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/boton1.png"))); // NOI18N
        jBPage1.setContentAreaFilled(false);
        jBPage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPage1MouseEntered(evt);
            }
        });
        jBPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 457, 30, 30));

        jBPage2.setText("2");
        jBPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jBPage3.setText("3");
        jBPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPage3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBPage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jBEje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BotonE1.png"))); // NOI18N
        jBEje1.setText("Eje1");
        jBEje1.setContentAreaFilled(false);
        getContentPane().add(jBEje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 95, 490, 80));

        jBEje2.setText("Eje2");
        getContentPane().add(jBEje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jBEje3.setText("Eje3");
        getContentPane().add(jBEje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jBEje4.setText("Eje4");
        getContentPane().add(jBEje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jBEje5.setText("Eje4");
        getContentPane().add(jBEje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jBEje6.setText("Eje4");
        getContentPane().add(jBEje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jBEje7.setText("Eje1");
        getContentPane().add(jBEje7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jBEje8.setText("Eje1");
        getContentPane().add(jBEje8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jBEje9.setText("Eje3");
        getContentPane().add(jBEje9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jBEje11.setText("Eje2");
        getContentPane().add(jBEje11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jBEje12.setText("Eje3");
        getContentPane().add(jBEje12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jBEje10.setText("Eje2");
        getContentPane().add(jBEje10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Boceto.png"))); // NOI18N
        Wallpaper.setFocusable(false);
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage1ActionPerformed
       limpiarPantalla(1);
    }//GEN-LAST:event_jBPage1ActionPerformed

    private void jBPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage2ActionPerformed
        limpiarPantalla(2);
    }//GEN-LAST:event_jBPage2ActionPerformed

    private void jBPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPage3ActionPerformed
        limpiarPantalla(3);
    }//GEN-LAST:event_jBPage3ActionPerformed

    private void jBPage1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPage1MouseEntered
        /*
            File file = new File ("imgs/Over1.png");
            jBPage1.setIcon((Icon) file);
            System.out.print(jBPage1.getIcon());
        */
    }//GEN-LAST:event_jBPage1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton jBEje1;
    private javax.swing.JButton jBEje10;
    private javax.swing.JButton jBEje11;
    private javax.swing.JButton jBEje12;
    private javax.swing.JButton jBEje2;
    private javax.swing.JButton jBEje3;
    private javax.swing.JButton jBEje4;
    private javax.swing.JButton jBEje5;
    private javax.swing.JButton jBEje6;
    private javax.swing.JButton jBEje7;
    private javax.swing.JButton jBEje8;
    private javax.swing.JButton jBEje9;
    private javax.swing.JButton jBPage1;
    private javax.swing.JButton jBPage2;
    private javax.swing.JButton jBPage3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
