/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S6_FigurasGeo;

/**
 *
 * @author Sergio Segura Vidal
 */
public class PerdirDatos extends javax.swing.JFrame {

    /**
     * Creates new form PerdirDatos
     */
    public PerdirDatos() 
    {
        initComponents();
        personalizar();
        setLocationRelativeTo(null);
    }

    public void personalizar ()
    {
        if (main.elementoSelect == 0)
        {
            jLDato1.setText("Valor del segmento");
            jTDato1.setText("Digite un numero positivo");
            
            jLDato2.setVisible(false);
            jTDato2.setVisible(false);
        }
        else
        {
            if (main.elementoSelect == 1)
            {
                jLDato1.setText("Valor del lado");
                jTDato1.setText("Digite un numero positivo");

                jLDato2.setVisible(false);
                jTDato2.setVisible(false);
            }
            else
            {
                jLDato1.setText("Valor del Largo");
                jTDato1.setText("Digite un numero positivo");
                
                jLDato2.setText("Valor del Ancho");
                jTDato2.setText("Digite un numero positivo");
            }
        } 
    }
    
    public void capturar ()
    {
        Resultado.dato1 = Double.parseDouble(jTDato1.getText().toString());
        if(jTDato2.isVisible() == true)
        {
            Resultado.dato2 = Double.parseDouble(jTDato2.getText().toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBListo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLDato1 = new javax.swing.JLabel();
        jTDato1 = new javax.swing.JTextField();
        jLDato2 = new javax.swing.JLabel();
        jTDato2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBListo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBListo.setText("Listo");
        jBListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite los datos");

        jLDato1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLDato1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDato1.setText("Dato 1");

        jTDato1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTDato1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDato1.setText("Digite dato 1");

        jLDato2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLDato2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDato2.setText("Dato 2");

        jTDato2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTDato2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDato2.setText("Digite dato 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jBListo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBListo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListoActionPerformed
        capturar();
        Resultado result = new Resultado ();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerdirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerdirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerdirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerdirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerdirDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBListo;
    private javax.swing.JLabel jLDato1;
    private javax.swing.JLabel jLDato2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTDato1;
    private javax.swing.JTextField jTDato2;
    // End of variables declaration//GEN-END:variables
}
