/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S6_FigurasGeo;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Segura Vidal
 */
public class Resultado extends javax.swing.JFrame 
{

    /**
     * Creates new form main
     */
    
    public static double dato1;
    public static double dato2;
    
   
    public Resultado() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        elementos();
        configurar();
        obtenerFigura();
    }
    
   public void elementos ()
   {
       colocarlogo(main.nombreFigura);
       
       if(main.elementoSelect == 0)
       {
            Linea lin = new Linea(dato1);
            lin.calcArea();
            lin.calcPerimetro();
            jTArea.setText(lin.area+"");
            jTPerimetro.setText(lin.perimetro+"");
       }
       else
       {
            if (main.elementoSelect == 1)
            {
                Cuadrado cua = new Cuadrado (dato1);
                cua.calcArea();
                cua.calcPerimetro();
                jTArea.setText(cua.area+"");
                jTPerimetro.setText(cua.perimetro+"");
            }
            else
            {
                Rectangulo rec = new Rectangulo(dato1, dato2);
                rec.calcArea();
                rec.calcPerimetro();
                jTArea.setText(rec.area+"");
                jTPerimetro.setText(rec.perimetro+"");
            }
       }
      
   }
    
   public void configurar ()
    {
        if (main.selecArea == true)
        {
            jTPerimetro.setText(" - ");
            jTPerimetro.setEditable(false);
        }
        else
        {
            if (main.selecPerimetro)
            {
                jTArea.setText(" - ");
                jTArea.setEditable(false);
            }
        }         
    }
    
    public void colocarlogo (String figura)
    {
        jLLogo.setIcon(new ImageIcon("src/imgs/"+figura+".png"));
    }
    
    public void obtenerFigura ()
    {
       jLNombreFigura.setText(main.nombreFigura);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLLogo = new javax.swing.JLabel();
        jTArea = new javax.swing.JTextField();
        jLNombreFigura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTPerimetro = new javax.swing.JTextField();
        jBListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Area");

        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N

        jTArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTArea.setText("Area");

        jLNombreFigura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLNombreFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombreFigura.setText("Nombre Figura...");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Perimetro");

        jTPerimetro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTPerimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPerimetro.setText("Perimetro");

        jBListo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBListo.setText("Listo");
        jBListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jBListo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLNombreFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLNombreFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBListo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListoActionPerformed
        main main = new main ();
        int respContinuar = JOptionPane.showOptionDialog(null,
                "¿Desea comprobar otra figura?",
                null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, null, null);
        if (respContinuar == 0)
        {        
            main.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jBListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBListo;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLNombreFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTArea;
    private javax.swing.JTextField jTPerimetro;
    // End of variables declaration//GEN-END:variables
}
